
module.exports = {
    CHANGE_STATUS_SUCCESS: 'Cập nhật status thành công',
    CHANGE_STATUS_MULTI_SUCCESS: 'Có %d phần tử được cập nhật status thành công',
    CHANGE_ORDERING_SUCCESS: 'Cập nhật ordering thành công',
    DELETE_SUCCESS: 'Xóa phần tử thành công',
    DELETE_MULTI_SUCCESS: 'Có %d phần tử được xóa thành công',
    ADD_SUCCESS: 'Thêm mới phần tử thành công',
    EDIT_SUCCESS: 'Cập nhật thông tin phần tử thành công',
    ERROR_NAME: 'Chiều dài từ %d đến %d ký tự',
    ERROR_ORDERING: 'Phải là số nguyên lớn hơn %d và bé hơn %d',
    ERROR_STATUS: 'Phải là một giá trị khác rỗng',
    CHANGE_GROUP_ACP_SUCCESS: 'Cập nhật GROUP ACP thành công',
    ERROR_GROUP:'Phải là một giá trị khác rỗng',
    ERROR_FILE_REQUIRE: 'Vui lòng chọn file upload',
    ERROR_FILE_LARGE: 'File quá lớn',
    CHANGE_SPECIAL_SUCCESS:'Cập nhật trạng thái bài viết thành công',
    ERROR_DESCRIPTION:'Chiều dài từ %d đến %d ký tự',
    ERROR_COPYRIGHT:'Chiều dài từ %d đến %d ký tự',
    ERROR_CONTENT:'Chiều dài từ %d đến %d ký tự',
};